### ISSUE TITLE
trying to put online using github pages 

### ISSUE THREAD

**Issue by ByteFlowGit** [zachey01/terminalPortfolio#1]
hello, 

Before all nice site implementatio you have here. 

I have re-use your code and now I want to put the site online using GitHub pages 

It allways giver 404 error ... 

Any special detail to make it online on gh-pages ? 

Thanks in advance !

**Comment by zachey01** [comment]
hello, hope this helps - https://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages

**Comment by ByteFlowGit** [comment]
Hello zachey,

Can you help me to construct the npm-gulp.yml to be executed in "actions"
of github so the site can be online inside github ?
As if is was your repository (then I think I can adapt).

How much do charge for this work ?

Kind regards,
Rui Gonçalves

**Comment by zachey01** [comment]
Hello, i created static build for github pages and other web hostings. I hope this helps you.

https://github.com/zachey01/terminalPortfolio/releases/download/1.1/build.zip
